url: http://amorvita.github.io
title: YoungJin Shin
description: Online Game Security, XIGNCODE, Geek, http://www.jiniya.net , Programmer, C/C++, Windows, Microsoft Visual C++ MVP, Grey's Anatomy, Steve Barakatt, Guillaume Musso, Sid Meier's Civilization IV, and World Of Warcraft.
language: en-us

author: YoungJin Shin
email: amorvita@live.com

github: amorvita
twitter: codemaru

analytics:
    profile: UA-444891-3

permalink: /:year/:month/:title

sitemap:
    include: ["/index.html"]

exclude: ["README.md"]
